name: Label Test
on:
#   issues:
#     types: [labeled]
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
